# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('platform', models.CharField(max_length=1000)),
                ('score', models.FloatField(default=0.0)),
                ('genre', models.CharField(max_length=1000)),
                ('editors_choice', models.BooleanField(default=False)),
            ],
        ),
    ]
